const tracery = require('tracery-es8');
export const getTyson = () => {
  const grammar = tracery.createGrammar({
    intro: [
      `most people don't know this, but`,
      `you wouldn't believe it, but`,
      `it's well known that`,
      `random fact:`,
      `despite popular belief,`,
    ],
    intake: ['breathful', 'gulp', 'inhalation', 'whiff', 'swallow', 'sniff'],
    intake2: ['breathe', 'gulp', 'inhale', 'whiff', 'swallow', 'sniff'],
    substance: [
      'air',
      'water',
      'nitrogen',
      'dust',
      'sand',
      'ozone',
      'galactic radiation',
      'carbon',
      'helium',
      'hydrogen',
      'argon',
      'fog',
      'steam',
      'plasma',
      'silicon',
    ],
    location: [
      'Earth',
      'Mars',
      'the Sun',
      'the Milky Way',
      'the universe',
      'North America',
      'Europe',
      'Antarctica',
      'the Moon',
      'Saturn',
      'the Andromeda galaxy',
      'Chicago',
      'your backyard',
      'the sky',
      'the Grand Canyon',
      'the Pacific Ocean',
    ],
    place: [
      'atmosphere',
      'surface',
      'crust',
      'core',
      'water volume',
      'biosphere',
      'history',
      'physical volume',
      'magnetic field',
      'surface tension',
    ],
    organSingle: [
      'esophagus',
      'brain',
      'heart',
      'circulatory system',
      'nervous system',
      'nerves',
    ],
    organPlural: ['lung', 'lymph node', 'ear', 'kidney'],
    organ: ['#organSingle#', '#organPlural.s#'],
    person: [
      'Abraham Lincoln',
      'Isaac Newton',
      'Barack Obama',
      'Socrates',
      'Napolean',
      'Mark Twain',
      'George Washington',
      'Julias Caesar',
      'Eddie Vedder',
      'Albert Einstein',
      'Beethoven',
      'Atilla the Hun',
      'Mother Theresa',
      'Betsy Ross',
      'Audrey Hepburn',
    ],
    howmanyintake: [
      'a single #intake#',
      'a small #intake#',
      'a large #intake#',
      'multiple #intake.s#',
      'daily #intake.s#',
      'a morning #intake#',
      'an evening #intake#',
      'regular #intake.s#',
      'occasional #intake.s#',
    ],
    particle: ['molecule', 'atom', 'compound', 'clump', 'cloud', 'radiation'],
    how: ['draws in', 'absorbs', 'ingests', 'accounts for'],
    thatmeans: [
      'That means',
      'So,',
      'So of course,',
      'That probably means',
      'So therefore',
      `So it's likely that`,
      'So surely,',
    ],
    howtravel: [
      'passed through',
      'circulated through',
      'traveled through',
      'absorbed into',
    ],
    haswas: ['has', 'was'],
    origin: [
      `#intro# #howmanyintake# of #substance# #how# more #substance# #particle.s# than there are #intake.s# of #substance# in #location#'s entire #place#. #thatmeans# some of the #substance# you just #intake2.ed# #haswas# #howtravel# the #organ# of #person#`,
    ],
  });

  grammar.addModifiers(tracery.baseEngModifiers);
  return grammar.flatten('#origin#');
};
