name: CI

on:
  push:
    branches: [main]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.
  #         yarn
  #         yarn run build
  #         yarn run test

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          name: Run a multi-line script
          run: >
            yarn &&
            yarn run build &&
            yarn run test

      - uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: >
            cd ~/code/m8b &&
            git pull &&
            nvm use --lts &&
            yarn &&
            yarn run test &&
            yarn run build &&
            pm2 restart index &&
            echo 'done'
