name: CI

on:
  push:
    branches: [main]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/code/m8b
            git pull 
            yarn
            yarn run test
            yarn run build
            pm2 restart index
            echo 'done'
